export const messages = {
    en: {
        hello:"hello",
        attendance:"attendance",
        history:"history",
        subject:"subject",
        room:"class",
        identify:"identify",
        fullName:"full name",
        status:"status",
        retainStatus:"retain",
        leaveStatus:"leave",
        onGoingStatus:"onGoing",
        offSchool:"off",
        onSchool:"on",
        offSchoolWithReason:"other",
        dayOff:"day off",
        confirm:"confirm",
        cancel:"cancel"
    },
    vi: {
        hello:"xin chào",
        attendance:"điểm danh",
        history:"lịch sử",
        subject:"môn",
        room:"lớp",
        identify:"số báo danh",
        fullName:"họ và tên",
        status:"tình trạng",
        offSchool:"nghỉ học",
        onSchool:"đi học",
        offSchoolWithReason:"có phép",
        retainStatus:"bảo lưu",
        leaveStatus:"nghỉ học",
        onGoingStatus:"đang học",
        dayOff:"số buổi nghỉ",
        confirm:"xác nhận",
        cancel:"từ chối"
    },
};
